[package]
name = "media-rtp"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
common = { path = "../common" }
tokio.workspace = true
bytes.workspace = true
tracing.workspace = true
rand.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
openh264 = "=0.6.5"
screencapturekit = { version = "=8.0.1", features = ["macos_13_0"] }
