[package]
name = "gb28181-simulator"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
common = { path = "../common" }
sip-core = { path = "../sip-core" }
gb28181-protocol = { path = "../gb28181-protocol" }
media-rtp = { path = "../media-rtp" }
encoding_rs = { workspace = true }
tokio.workspace = true
tracing.workspace = true
rand.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
